services:
  securevault-db:
    image: postgres:18
    container_name: securevault-db
    environment:
      POSTGRES_DB: securevault
      POSTGRES_USER: securevault
      POSTGRES_PASSWORD: securevault
    ports:
      - "5000:5432"
    volumes:
      - db:/var/lib/postgresql

  keycloak-db:
    image: postgres:18
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db:/var/lib/postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: securevault-keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8001:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes

  redis:
    image: redis:7
    container_name: securevault-redis
    ports:
      - "6000:6379"
    volumes:
      - redis:/data

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: securevault-kafka
    ports:
      - "9000:9092"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9000
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka:/var/lib/kafka/data

volumes:
  db:
  keycloak-db:
  redis:
  kafka: