spring:
  application:
    name: securevault

  datasource:
    url: jdbc:postgresql://localhost:5000/securevault
    username: securevault
    password: securevault

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration/public
    schemas: public
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379

security:
  jwt:
    secret: vTpTSehgudwctoSkCRB3HCdrW8NJBRA1s02pf7TXh9E
    access-token-expiration: 900000      # 15 minutes in ms
    refresh-token-expiration: 604800000  # 7 days in ms
  cookie:
    access-token-cookie-name: securevault-access-token
    refresh-token-cookie-name: securevault-refresh-token
    refresh-token-cookie-path: /platform/auth/refresh
  redis:
    bootstrap-token-ttl-hours: 24
    bootstrap-token-prefix: 'bootstrap:'
    invite-token-ttl-hours: 72
    invite-token-prefix: 'invite:'
