spring:
  application:
    name: securevault

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5000/securevault
    username: securevault
    password: securevault

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

data:
  redis:
    ttl: 10
    prefix: 'pending_oauth2:'
security:
  jwt:
    secret: vTpTSehgudwctoSkCRB3HCdrW8NJBRA1s02pf7TXh9E
    access-token-expiration: 900000      # 15 minutes in ms
    refresh-token-expiration: 604800000  # 7 days in ms
  cookie:
    access-token-cookie-name: securevault-access-token
    refresh-token-cookie-name: securevault-refresh-token
    refresh-token-cookie-path: /auth/refresh
    oauth2-request-cookie-name: securevault-oauth2-request
    oauth2-request-cookie-max-age: 180
    oauth2-pending-reg-request-cookie-name: securevault-oauth2-pending-reg-request
    oauth2-pending-reg-request-cookie-path: /oauth2/pending-registration
    oauth2-linking-request-cookie-name: securevault-oauth2-linking-request
  oauth2:
    success-redirect-url: http://localhost:3000/me.html
    pending-reg-redirect-url: http://localhost:3000/pending-reg.html
    provider-email-attributes:
      google: email
#      spotify: email
    provider-id-attributes:
      google: sub
#      spotify: id
