server:
  port: 8000

spring:
  application:
    name: securevault

  datasource:
    url: jdbc:postgresql://localhost:5000/securevault
    username: securevault
    password: securevault

  data:
    redis:
      host: localhost
      port: 6000

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8001/realms/app-realm

security:
  keycloak:
    realm: app-realm
    auth-server-url: http://localhost:8001
    client-id: backend-client
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
  cookie:
    access-token-cookie-name: securevault-access-token
    refresh-token-cookie-name: securevault-refresh-token
    refresh-token-cookie-path: /auth/refresh